service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false
  serviceName: transactions
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/framework/functions

functions:
  createTransaction:
    handler: ${self:custom.funcDir}/createTransaction.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: post
          cors:
            origin: '*'
            headers: '*'
