service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  memorySize: 512
  apiGateway:
    restApiId: ${ssm:/coinc/infra/api-gateway/id}
    restApiRootResourceId: ${ssm:/coinc/infra/api-gateway/root-resource-id}

  environment:
    DB_HOST: ${ssm:/coinc/infra/db_host}
    DB_USER: ${ssm:/coinc/infra/db_user}
    DB_PASSWORD: ${ssm:/coinc/infra/db_password}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false
  serviceName: transactions
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/framework/functions

functions:
  createTransaction:
    handler: ${self:custom.funcDir}/transactions/createTransaction.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: post
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'POST'
  getTransaction:
    handler: ${self:custom.funcDir}/transactions/getTransaction.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{transactionId}
          method: get
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'GET'
  listTransactions:
    handler: ${self:custom.funcDir}/transactions/listTransactions.handler
    events:
      - http:
          path: ${self:custom.baseApi}
          method: get
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'GET'
  deleteTransaction:
    handler: ${self:custom.funcDir}/transactions/deleteTransaction.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{transactionId}
          method: delete
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'DELETE'
  createCategory:
    handler: ${self:custom.funcDir}/categories/createCategory.handler
    events:
      - http:
          path: ${self:custom.baseApi}/category
          method: post
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'POST'
  deleteCategory:
    handler: ${self:custom.funcDir}/categories/deleteCategory.handler
    events:
      - http:
          path: ${self:custom.baseApi}/category/{categoryId}
          method: delete
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'DELETE'
  updateCategory:
    handler: ${self:custom.funcDir}/categories/updateCategory.handler
    events:
      - http:
          path: ${self:custom.baseApi}/category/
          method: put
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'PUT'
  listCategory:
    handler: ${self:custom.funcDir}/categories/listCategories.handler
    events:
      - http:
          path: ${self:custom.baseApi}/category
          method: get
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'GET'
  getSchedule:
    handler: ${self:custom.funcDir}/schedules/getSchedule.handler
    events:
      - http:
          path: ${self:custom.baseApi}/schedules/{scheduleId}
          method: get
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'GET'
  createSchedule:
    handler: ${self:custom.funcDir}/schedules/createSchedule.handler
    events:
      - http:
          path: ${self:custom.baseApi}/schedules
          method: post
  deleteSchedule:
    handler: ${self:custom.funcDir}/schedules/deleteSchedule.handler
    events:
      - http:
          path: ${self:custom.baseApi}/schedules/{scheduleId}
          method: delete
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'DELETE'
  listSchedules:
    handler: ${self:custom.funcDir}/schedules/listSchedules.handler
    events:
      - http:
          path: ${self:custom.baseApi}/schedules
          method: get
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'GET'
  updateSchedules:
    handler: ${self:custom.funcDir}/schedules/updateSchedule.handler
    events:
      - http:
          path: ${self:custom.baseApi}/schedules/
          method: put
          cors:
            - enabled: true
            - origin: '*'
            - headers: '*'
            - methods: 'PUT'
