name: "AWS"
description: ""
inputs:
  role-to-assume:
    description: 'role-to-assume'
    required: true
  aws-region:
    description: 'aws-region'
    required: true
    default: 'us-east-1'
runs:
  using: "composite"
  steps:
    - name: AWS - Configure credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
