name: DEV

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: aws-actions/configure-aws-credentials@1b511abead59c6ce207077c0bf0e0043b1382612
        with:
          role-to-assume: arn:aws:iam::882227338556:role/coinc-ms-bank-accounts-dev-us-east-1-lambdaRole
          aws-region: us-east-1

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: AWS Configure credentials
        uses: ./devops/github-actions/aws
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Serverless Deploy
        uses: ./devops/github-actions/serverless-deploy
        with:
          stage: dev
